<?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<NamedLayer><Name>scbviarioapgou</Name><UserStyle><Name>scbviarioapgou:_:bezapgouvi:_:default:bezapgouvi</Name><Title>scbviarioapgou:_:bezapgouvi:_:default:bezapgouvi</Title><Abstract>scbviarioapgou:_:bezapgouvi:_:default:bezapgouvi</Abstract><FeatureTypeStyle><Name>bezapgouvi</Name><Rule><Name>Viario 1er orden Existente</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 1er orden Existente</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke'>#666666</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>2</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Viario 1er orden Propuesto</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 1er orden Propuesto</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke-dasharray'>4.0 4.0</CssParameter><CssParameter name='stroke'>#990000</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1.0</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Viario 2º orden Existente</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 2º orden Existente</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke'>#999999</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1.5</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Viario 2º orden Propuesto</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 2º orden Propuesto</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke-dasharray'>4.0 4.0</CssParameter><CssParameter name='stroke'>#ff3333</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1.5</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Viario 3er orden Existente</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 3er orden Existente</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke'>#999999</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Viario 3er orden Propuesto</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>Viario 3er orden Propuesto</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke-dasharray'>4.0 4.0</CssParameter><CssParameter name='stroke'>#ff3333</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>viario-EXTERIOR</Name><ogc:Filter xmlns:ogc='http://www.opengis.net/ogc'><ogc:PropertyIsEqualTo><ogc:PropertyName>tipo</ogc:PropertyName><ogc:Literal>viario-EXTERIOR</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name='stroke'>#215bac</CssParameter><CssParameter name='stroke-linejoin'>round</CssParameter><CssParameter name='stroke-opacity'>1.0</CssParameter><CssParameter name='stroke-linecap'>round</CssParameter><CssParameter name='stroke-width'><ogc:Literal>1</ogc:Literal></CssParameter></Stroke></LineSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer>
</StyledLayerDescriptor>
