<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0">
<NamedLayer><Name>tramosabastecimiento</Name><UserStyle><Name>tramosabastecimiento:_:RedDeDistribucionPorMaterial</Name><Title>tramosabastecimiento:_:tramosabastecimiento:_:RedDeDistribucionPorMaterial</Title><FeatureTypeStyle><Name>Red de distribucion</Name><Rule><Name>Red de distribucion [FC]</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>MATDIS</ogc:PropertyName><ogc:Literal>FC</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name="stroke">#FF0000</CssParameter><CssParameter name="stroke-width">3</CssParameter><CssParameter name="stroke-linecap">square</CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Red de distribucion [HO]</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>MATDIS</ogc:PropertyName><ogc:Literal>HO</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name="stroke">#00FF00</CssParameter><CssParameter name="stroke-width">3</CssParameter><CssParameter name="stroke-linecap">square</CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Red de distribucion [OT]</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>MATDIS</ogc:PropertyName><ogc:Literal>OT</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name="stroke">#0000FF</CssParameter><CssParameter name="stroke-width">3</CssParameter><CssParameter name="stroke-linecap">square</CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Red de distribucion [PC]</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>MATDIS</ogc:PropertyName><ogc:Literal>PC</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name="stroke">#FFFF00</CssParameter><CssParameter name="stroke-width">3</CssParameter><CssParameter name="stroke-linecap">square</CssParameter></Stroke></LineSymbolizer></Rule><Rule><Name>Red de distribucion [PE]</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>MATDIS</ogc:PropertyName><ogc:Literal>PE</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
<MinScaleDenominator>0.0</MinScaleDenominator><MaxScaleDenominator>9.0E99</MaxScaleDenominator><LineSymbolizer><Stroke><CssParameter name="stroke">#00FFFF</CssParameter><CssParameter name="stroke-width">3</CssParameter><CssParameter name="stroke-linecap">square</CssParameter></Stroke></LineSymbolizer></Rule></FeatureTypeStyle></UserStyle></NamedLayer>
</StyledLayerDescriptor>
